spring:
  profiles:
    active: dev # dev:开发环境 || prod:生产环境
  application:
    name: AutoMotiveMes
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss  # 对 Date 有效
  web:
    resources:
      add-mappings: false  # 禁用默认静态资源处理

security:
  jwt:
    expiration: 86400 # 公共过期时间(1天)