server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://111.229.150.28:3306/auto_motive_mes?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: redis.prod.example.com
      port: 6379
      lettuce:
        pool:
          max-active: 16
          max-idle: 16
          min-idle: 4

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 172800  # 48小时