server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_motive_mes?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: zyntm123lhy
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

security:
  jwt:
    secret: ThisIsASecretKeyWithAtLeast32BytesForHS256zyntm123lhy